#!/usr/bin/env python3
"""WP19 low-mode backreaction scout.

NON-RIGOROUS diagnostic. Uses saved lower and higher predictor trajectories.
It measures the low-mode forcing generated by the higher-cutoff shell:

  R_N = || P_N [ B(v,h) + B(h,v) + B(h,h) ] ||_2

with v=P_N u_{N+1}, h=(I-P_N)u_{N+1}.

This is not a lower-cutoff-only certificate and is not a continuum bound.
"""

from __future__ import annotations
import argparse
import json
import math
import sys
from pathlib import Path
import numpy as np

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--repo",type=Path,required=True)
    ap.add_argument("--N",type=int,required=True)
    ap.add_argument("--lower-nodes",type=Path,required=True)
    ap.add_argument("--higher-nodes",type=Path,required=True)
    ap.add_argument("--higher-rhs",type=Path,required=True)
    ap.add_argument("--lower-sampled-strain",type=Path,required=True)
    ap.add_argument("--output",type=Path,required=True)
    args=ap.parse_args()

    sys.path.insert(0,str(args.repo.resolve()/"src"))
    from wp16_036_dealiased_trajectory_gate import DealiasedSystem

    low=DealiasedSystem(args.N)
    high=DealiasedSystem(args.N+1)

    L=np.load(args.lower_nodes,mmap_mode="r")
    H=np.load(args.higher_nodes,mmap_mode="r")
    Rhs=np.load(args.higher_rhs,mmap_mode="r")
    strain=json.loads(args.lower_sampled_strain.read_text())["values"]

    lowidx=np.array([high.index[k] for k in low.modes],dtype=int)
    newmask=np.array([k not in low.index for k in high.modes],dtype=bool)

    rows=[]
    for j in range(len(L)):
        aH=np.asarray(H[j])
        v=np.zeros_like(aH)
        v[lowidx]=aH[lowidx]

        nonlinear_full=-np.asarray(Rhs[j])-high.nu*high.square[:,None]*aH
        back=(nonlinear_full-high.nonlinear(v))[lowidx]

        rows.append({
            "node":j,
            "backreaction_L2":float(np.linalg.norm(back.ravel())),
            "low_drift_L2":float(np.linalg.norm((aH[lowidx]-np.asarray(L[j])).ravel())),
            "new_shell_L2":float(np.linalg.norm(aH[newmask].ravel()))
        })

    h=0.000025
    E=0.0
    for j in range(len(rows)-1):
        S=float(strain[j])
        R=rows[j]["backreaction_L2"]
        x=S*h
        E=math.exp(x)*E+R*(math.expm1(x)/S if S else h)

    result={
        "status":"NON-RIGOROUS higher-trajectory backreaction scout",
        "transition":f"{args.N}->{args.N+1}",
        "max_sampled_low_backreaction":max(r["backreaction_L2"] for r in rows),
        "sampled_backreaction_integral":h*sum(r["backreaction_L2"] for r in rows[:-1]),
        "sampled_recurrence_using_lower_physical_strain":E,
        "actual_low_mode_endpoint_drift":rows[-1]["low_drift_L2"],
        "actual_new_shell_endpoint_norm":rows[-1]["new_shell_L2"],
        "rows":rows
    }
    args.output.write_text(json.dumps(result,indent=2)+"\n")
    print(json.dumps({k:v for k,v in result.items() if k!="rows"},indent=2))

if __name__=="__main__":
    main()
